/**
 * Full Connecticut municipality catalog by county (169 towns/cities).
 * Seeded into `ct_counties` / `ct_towns` — not wired into public pages yet.
 */

export type CtCountySeed = {
  id: string
  name: string
  sortOrder: number
  towns: readonly string[]
}

/** Fairfield County towns that ship active today (matches TMRE_TOWNS). */
export const CT_DEFAULT_ACTIVE_TOWNS = [
  'Norwalk',
  'New Canaan',
  'Westport',
  'Wilton',
  'Weston',
  'Fairfield',
  'Ridgefield',
] as const

/** SmartMLS city codes for the default-active towns (from tmre-towns). */
export const CT_DEFAULT_MLS_CITY_CODES: Record<string, string> = {
  Norwalk: '350',
  'New Canaan': '310',
  Westport: '540',
  Wilton: '550',
  Weston: '530',
  Fairfield: '200',
  Ridgefield: '390',
}

export const CT_COUNTY_TOWN_SEED: readonly CtCountySeed[] = [
  {
    id: 'fairfield',
    name: 'Fairfield',
    sortOrder: 1,
    towns: [
      'Bethel',
      'Bridgeport',
      'Brookfield',
      'Danbury',
      'Darien',
      'Easton',
      'Fairfield',
      'Greenwich',
      'Monroe',
      'New Canaan',
      'New Fairfield',
      'Newtown',
      'Norwalk',
      'Redding',
      'Ridgefield',
      'Shelton',
      'Sherman',
      'Stamford',
      'Stratford',
      'Trumbull',
      'Weston',
      'Westport',
      'Wilton',
    ],
  },
  {
    id: 'hartford',
    name: 'Hartford',
    sortOrder: 2,
    towns: [
      'Avon',
      'Berlin',
      'Bloomfield',
      'Bristol',
      'Burlington',
      'Canton',
      'East Granby',
      'East Hartford',
      'East Windsor',
      'Enfield',
      'Farmington',
      'Glastonbury',
      'Granby',
      'Hartford',
      'Hartland',
      'Manchester',
      'Marlborough',
      'New Britain',
      'Newington',
      'Plainville',
      'Rocky Hill',
      'Simsbury',
      'South Windsor',
      'Southington',
      'Suffield',
      'West Hartford',
      'Wethersfield',
      'Windsor',
      'Windsor Locks',
    ],
  },
  {
    id: 'litchfield',
    name: 'Litchfield',
    sortOrder: 3,
    towns: [
      'Barkhamsted',
      'Bethlehem',
      'Bridgewater',
      'Canaan',
      'Colebrook',
      'Cornwall',
      'Goshen',
      'Harwinton',
      'Kent',
      'Litchfield',
      'Morris',
      'New Hartford',
      'New Milford',
      'Norfolk',
      'North Canaan',
      'Plymouth',
      'Roxbury',
      'Salisbury',
      'Sharon',
      'Thomaston',
      'Torrington',
      'Warren',
      'Washington',
      'Watertown',
      'Winchester',
      'Woodbury',
    ],
  },
  {
    id: 'middlesex',
    name: 'Middlesex',
    sortOrder: 4,
    towns: [
      'Chester',
      'Clinton',
      'Cromwell',
      'Deep River',
      'Durham',
      'East Haddam',
      'East Hampton',
      'Essex',
      'Haddam',
      'Killingworth',
      'Middlefield',
      'Middletown',
      'Old Saybrook',
      'Portland',
      'Westbrook',
    ],
  },
  {
    id: 'new-haven',
    name: 'New Haven',
    sortOrder: 5,
    towns: [
      'Ansonia',
      'Beacon Falls',
      'Bethany',
      'Branford',
      'Cheshire',
      'Derby',
      'East Haven',
      'Guilford',
      'Hamden',
      'Madison',
      'Meriden',
      'Middlebury',
      'Milford',
      'Naugatuck',
      'New Haven',
      'North Branford',
      'North Haven',
      'Orange',
      'Oxford',
      'Prospect',
      'Seymour',
      'Southbury',
      'Wallingford',
      'Waterbury',
      'West Haven',
      'Wolcott',
      'Woodbridge',
    ],
  },
  {
    id: 'new-london',
    name: 'New London',
    sortOrder: 6,
    towns: [
      'Bozrah',
      'Colchester',
      'East Lyme',
      'Franklin',
      'Griswold',
      'Groton',
      'Lebanon',
      'Ledyard',
      'Lisbon',
      'Lyme',
      'Montville',
      'New London',
      'North Stonington',
      'Norwich',
      'Old Lyme',
      'Preston',
      'Salem',
      'Sprague',
      'Stonington',
      'Voluntown',
      'Waterford',
    ],
  },
  {
    id: 'tolland',
    name: 'Tolland',
    sortOrder: 7,
    towns: [
      'Andover',
      'Bolton',
      'Columbia',
      'Coventry',
      'Ellington',
      'Hebron',
      'Mansfield',
      'Somers',
      'Stafford',
      'Tolland',
      'Union',
      'Vernon',
      'Willington',
    ],
  },
  {
    id: 'windham',
    name: 'Windham',
    sortOrder: 8,
    towns: [
      'Ashford',
      'Brooklyn',
      'Canterbury',
      'Chaplin',
      'Eastford',
      'Hampton',
      'Killingly',
      'Plainfield',
      'Pomfret',
      'Putnam',
      'Scotland',
      'Sterling',
      'Thompson',
      'Windham',
      'Woodstock',
    ],
  },
]

export function ctTownSlug(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}
