import type { TownBudgetSnapshot } from '@/lib/town-budget/types'

/** Westport FY 2026–2027 — sourced from Town Taxpayer's Guide PDF. */
export const westportFy2027: TownBudgetSnapshot = {
  town: 'Westport',
  fiscalYear: '2026–2027',
  sourceLabel: "Town of Westport Taxpayer's Guide (FY 2026/2027)",
  sourceUrl: 'https://www.westportct.gov/taxcollector',
  millRate: {
    current: 13.2,
    prior: 18.86,
    changePct: -30.01,
  },
  totalBudget: 266_062_614,
  stateAssistance: 2_272_518,
  fundBalanceReservePct: 12.1,
  highlights: [
    'Total approved budget of $266.1M; schools receive 63.45% ($168.8M).',
    'Mill rate set at 13.20 — down 30.01% from the prior year (18.86), largely reflecting the 2025 revaluation.',
    'School spending up $11.2M (7.09%); general town spending up $1.7M (1.96%).',
    'Grand List up ~50% from revaluation: residential +60%, commercial +16%; modest gains in personal property (+1%) and motor vehicles (+6%).',
    '$11.85M drawn from Fund Balance Reserve; fund balance remains at a conservative 12.1% (Aaa bond rating).',
    'Without estimated state assistance ($2.27M), mill rate would be approximately 13.30.',
  ],
  allocation: [
    {
      id: 'schools',
      label: 'Westport Public Schools',
      amount: 168_818_947,
      sharePct: 63.45,
    },
    {
      id: 'town',
      label: 'Town Government',
      amount: 89_539_349,
      sharePct: 33.65,
    },
    {
      id: 'outside',
      label: 'Outside Agencies',
      amount: 7_704_318,
      sharePct: 2.9,
    },
  ],
  revenues: [
    {
      id: 'taxes',
      label: 'Taxes (current & prior years)',
      amount: 229_300_149,
      sharePct: 86.18,
    },
    {
      id: 'education',
      label: 'Education revenue',
      amount: 1_337_740,
      sharePct: 0.5,
    },
    {
      id: 'recreation',
      label: 'Recreation revenue',
      amount: 7_786_755,
      sharePct: 2.93,
    },
    {
      id: 'other',
      label: 'Other sources',
      amount: 15_787_970,
      sharePct: 5.93,
    },
    {
      id: 'fund-balance',
      label: 'Fund balance draw down',
      amount: 11_850_000,
      sharePct: 4.45,
    },
  ],
  expenditures: [
    {
      id: 'general',
      label: 'General government',
      amount: 8_531_484,
      sharePct: 3.21,
    },
    {
      id: 'safety',
      label: 'Public safety',
      amount: 28_567_135,
      sharePct: 10.74,
    },
    {
      id: 'works',
      label: 'Public works',
      amount: 14_614_891,
      sharePct: 5.49,
    },
    {
      id: 'health',
      label: 'Health',
      amount: 624_653,
      sharePct: 0.23,
    },
    {
      id: 'human',
      label: 'Human services',
      amount: 1_808_290,
      sharePct: 0.68,
    },
    {
      id: 'education',
      label: 'Education',
      amount: 168_818_947,
      sharePct: 63.45,
    },
    {
      id: 'library',
      label: 'Library',
      amount: 6_515_349,
      sharePct: 2.45,
    },
    {
      id: 'parks',
      label: 'Parks & recreation',
      amount: 9_811_907,
      sharePct: 3.69,
    },
    {
      id: 'pension',
      label: 'Pension, OPEB, insurance & misc.',
      amount: 21_123_160,
      sharePct: 7.94,
    },
    {
      id: 'debt',
      label: 'Debt service',
      amount: 4_278_633,
      sharePct: 1.61,
    },
    {
      id: 'other-fin',
      label: 'Other financial uses',
      amount: 1_368_165,
      sharePct: 0.51,
    },
  ],
  taxCalendar: [
    { month: 'Jul', day: '1', note: 'First installment — real estate, personal property, motor vehicle, sewer/use.' },
    { month: 'Aug', day: '31', note: 'Last day to pay first installment without penalty.' },
    { month: 'Oct', day: '1', note: 'Second installment due; Grand List (assessment) date.' },
    { month: 'Nov', day: '2', note: 'Last day to pay second installment without penalty.' },
    { month: 'Dec', day: '—', note: 'Supplemental motor vehicle tax bills mailed.' },
    { month: 'Jan', day: '1', note: 'Third installment; supplemental motor vehicle due in full.' },
    { month: 'Feb', day: '1', note: 'Last day for Jan. 1 installment without penalty.' },
    { month: 'Apr', day: '1', note: 'Fourth installment — real estate, personal property, sewer/use.' },
    { month: 'May', day: '—', note: 'Real estate tax lien notices and sewer use/assessment sent.' },
    { month: 'May', day: '3', note: 'Last day for Apr. 1 installment without penalty.' },
  ],
  contacts: {
    taxCollectorPhone: '(203) 341-1060',
    taxCollectorEmail: 'taxcollector@westportct.gov',
    taxCollectorUrl: 'https://www.westportct.gov/taxcollector',
    payTaxesUrl: 'https://www.westportct.gov/paytaxes',
    payTaxesLabel: 'westportct.gov/paytaxes',
    assessorPhone: '(203) 341-1070',
    townHallAddress: '110 Myrtle Avenue, Westport, CT 06880',
  },
}
