import type { BoardPreviewListing } from "@/components/intelligence/board-preview/types";

/** Fallback when live API is unavailable — no real photo proxies. */
export const BOARD_PREVIEW_MOCK_LISTINGS: BoardPreviewListing[] = [
  {
    key: "preview-1",
    score: 92.4,
    address: "27 Rowayton Woods Dr",
    city: "Norwalk",
    type: "SFR",
    beds: 4,
    baths: 2.5,
    price: 695000,
    pricePerSqft: 378,
    sqft: 1840,
    dom: 4,
    status: "New",
    photoCount: 28,
    headline: "Top-block Rowayton — rarely available",
  },
  {
    key: "preview-2",
    score: 86.1,
    address: "14 Devil's Garden Rd",
    city: "Norwalk",
    type: "SFR",
    beds: 5,
    baths: 3,
    price: 769000,
    pricePerSqft: 364,
    sqft: 2110,
    dom: 9,
    status: "Active",
    photoCount: 34,
    headline: "Contemporary design, recently updated",
  },
  {
    key: "preview-3",
    score: 81.3,
    address: "42 Cross Hwy",
    city: "Westport",
    type: "SFR",
    beds: 5,
    baths: 4,
    price: 1690000,
    pricePerSqft: 532,
    sqft: 3178,
    dom: 5,
    status: "New",
    photoCount: 41,
    headline: "Trophy location — rarely available",
  },
  {
    key: "preview-4",
    score: 76.8,
    address: "311 Hillspoint Rd",
    city: "Westport",
    type: "SFR",
    beds: 6,
    baths: 5,
    price: 2150000,
    pricePerSqft: 504,
    sqft: 4270,
    dom: 7,
    status: "Active",
    photoCount: 52,
    headline: "Grand scale with exceptional living space",
  },
  {
    key: "preview-5",
    score: 72.2,
    address: "47 Sylvan Rd S",
    city: "Westport",
    type: "SFR",
    beds: 4,
    baths: 3,
    price: 1395000,
    pricePerSqft: 462,
    sqft: 3020,
    dom: 14,
    status: "Reduced",
    photoCount: 36,
    headline: "Updated interiors on quiet street",
  },
  {
    key: "preview-6",
    score: 68.5,
    address: "9 Cedar Crest Pl",
    city: "Norwalk",
    type: "Condo",
    beds: 2,
    baths: 2,
    price: 449000,
    pricePerSqft: 396,
    sqft: 1135,
    dom: 22,
    status: "Active",
    photoCount: 18,
    headline: "Low-maintenance living in prime location",
  },
];
